package com.dream.myLife;

import com.dream.myLife.user.entity.UPermission;
import com.dream.myLife.user.entity.UPermissionCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    long countByExample(UPermissionCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    int deleteByExample(UPermissionCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    int insert(UPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    int insertSelective(UPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    List<UPermission> selectByExample(UPermissionCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    UPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UPermission record, @Param("example") UPermissionCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UPermission record, @Param("example") UPermissionCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UPermission record);
}