package com.dream.myLife;

import com.dream.myLife.user.entity.URolePermission;
import com.dream.myLife.user.entity.URolePermissionCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface URolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    long countByExample(URolePermissionCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int deleteByExample(URolePermissionCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int insert(URolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(URolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    List<URolePermission> selectByExample(URolePermissionCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") URolePermission record, @Param("example") URolePermissionCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") URolePermission record, @Param("example") URolePermissionCondition example);
}