package com.dream.myLife.user.entity;

import java.io.Serializable;

public class URolePermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_role_permission.rid
     *
     * @mbg.generated
     */
    private Long rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_role_permission.pid
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_role_permission.rid
     *
     * @return the value of u_role_permission.rid
     *
     * @mbg.generated
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_role_permission.rid
     *
     * @param rid the value for u_role_permission.rid
     *
     * @mbg.generated
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_role_permission.pid
     *
     * @return the value of u_role_permission.pid
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_role_permission.pid
     *
     * @param pid the value for u_role_permission.pid
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }
}